<?php

namespace App\Repository;

use App\Entity\Post;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Post::class);
    }

    /**
     * Add a fetchmode Eager for categories
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function createQueryBuilderWithCategory () {
        return $this->createQueryBuilder("p")
            ->leftJoin("p.category", "c")
            ->addSelect("c")
            ->orderBy("p.createdAt", "DESC");
    }

    public function createQueryBuilderWithUser () {
        return $this->createQueryBuilder("p")
            ->leftJoin("p.user", "u")
            ->addSelect("u")
            ->orderBy("p.createdAt", "DESC");
    }

    public function createQueryBuilderWithUserAndCategory () {
        return $this->createQueryBuilder("p")
            ->leftJoin("p.category", "c")
            ->addSelect("c")
            ->leftJoin("p.user", "u")
            ->addSelect("u")
            ->orderBy("p.createdAt", "DESC");
    }

}
