app:
    resource: "../src/Controller/"
    type:     annotation

admin:
    # name_prefix: admin_
    prefix:     "%admin_prefix%"
    resource:   "../src/Controller/Admin/"
    type:       annotation